package com.shoppingCart.Model;
// Generated Nov 17, 2016 7:16:37 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VendorDetails generated by hbm2java
 */
@Entity
@Table(name = "vendorDetails", catalog = "shopping_cart_schema")
public class VendorDetails implements java.io.Serializable {

	private int vendorId;
	private String vendorName;
	private String vendorEmail;

	public VendorDetails() {
	}

	public VendorDetails(int vendorId) {
		this.vendorId = vendorId;
	}

	public VendorDetails(int vendorId, String vendorName, String vendorEmail) {
		this.vendorId = vendorId;
		this.vendorName = vendorName;
		this.vendorEmail = vendorEmail;
	}

	@Id

	@Column(name = "vendor_id", unique = true, nullable = false)
	public int getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(int vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "vendor_name", length = 45)
	public String getVendorName() {
		return this.vendorName;
	}

	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}

	@Column(name = "vendor_email", length = 45)
	public String getVendorEmail() {
		return this.vendorEmail;
	}

	public void setVendorEmail(String vendorEmail) {
		this.vendorEmail = vendorEmail;
	}

}
